### ISSUE TITLE
TypeError: UUID objects are immutable (fastapi_users)

### ISSUE THREAD

**Issue by BhuwanPandey** [aminalaee/sqladmin#765]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Hy there,
I am using fastapi_users for authentication .

Here is the code,
inside app directory
app.py
```
from contextlib import asynccontextmanager
from fastapi import FastAPI
from sqladmin import Admin, ModelView
from app.db import User, create_db_and_tables, engine


@asynccontextmanager
async def lifespan(app: FastAPI):
    await create_db_and_tables()
    yield


app = FastAPI(lifespan=lifespan)

admin = Admin(app, engine)
class UserAdmin(ModelView, model=User):
    ...
admin.add_view(UserAdmin)

```

in db.py
```
from typing import AsyncGenerator

from fastapi import Depends
from fastapi_users.db import SQLAlchemyBaseUserTableUUID, SQLAlchemyUserDatabase
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase

DATABASE_URL = "sqlite+aiosqlite:///./test.db"


class Base(DeclarativeBase):
    pass


class User(SQLAlchemyBaseUserTableUUID, Base):
    pass


engine = create_async_engine(DATABASE_URL)
async_session_maker = async_sessionmaker(engine, expire_on_commit=False)


async def create_db_and_tables():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def get_async_session() -> AsyncGenerator[AsyncSession, None]:
    async with async_session_maker() as session:
        yield session


async def get_user_db(session: AsyncSession = Depends(get_async_session)):
    yield SQLAlchemyUserDatabase(session, User)

```
in main.py
```
import uvicorn

if __name__ == "__main__":
    uvicorn.run("app.app:app", host="0.0.0.0", log_level="info", port=8000, reload=True)

```
```
directory structure
project 
    -app 
       - app.py
       - db.py
   -main.py

python main.py to run program
```
requirements.txt
```
fastapi
fastapi-users[sqlalchemy]
uvicorn[standard]
aiosqlite
sqladmin
```

this line generate issue
https://github.com/aminalaee/sqladmin/blob/cdff6b4a641448099133b79f2d941f55f288bf29/sqladmin/helpers.py#L229

### Steps to reproduce the bug

This issue arise when I  visit details and edit section , just for example
http://127.0.0.1:8000/admin/user/details/0ab165e9-7408-45ef-8179-c2d5f18f44fb
http://127.0.0.1:8000/admin/user/edit/0ab165e9-7408-45ef-8179-c2d5f18f44fb
 

### Environment

- window 11 , python 3.11
-

**Comment by aminalaee** [comment]
please provide the traceback and take a look at previous issues: https://github.com/aminalaee/sqladmin/issues/668

**Comment by aminalaee** [comment]
I saw that this is already fixed in CPython and merged in Python 3.11 and 3.12: https://github.com/python/cpython/pull/115213

**Comment by BhuwanPandey** [comment]
> I saw that this is already fixed in CPython and merged in Python 3.11 and 3.12: [python/cpython#115213](https://github.com/python/cpython/pull/115213)

I don't know why, I am still getting this error eventhough I switch to 3.11.1 , previously  I used 3.11.0 
I am using pyenv for package management

```
  File "C:\Users\HP\fastapi-users-dev\envv\Lib\site-packages\sqladmin\models.py", line 815, in get_object_for_details
    stmt = self._stmt_by_identifier(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\fastapi-users-dev\envv\Lib\site-packages\sqladmin\models.py", line 833, in _stmt_by_identifier
    values = object_identifier_values(identifier, self.model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\fastapi-users-dev\envv\Lib\site-packages\sqladmin\helpers.py", line 229, in object_identifier_values
    value = False if type_ is bool and part == "False" else type_(part)
                                                            ^^^^^^^^^^^
  File "C:\Users\HP\.pyenv\pyenv-win\versions\3.11.1\Lib\typing.py", line 1247, in __call__
    result.__orig_class__ = self
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.pyenv\pyenv-win\versions\3.11.1\Lib\uuid.py", line 278, in __setattr__
    raise TypeError('UUID objects are immutable')
TypeError: UUID objects are immutable
```
What do you think am I missing?

**Comment by aminalaee** [comment]
it is not released yet, for now you can use the workaround mentioned in the other issue, but whenever this is released you can use it without the workaround: https://docs.python.org/3.11/whatsnew/changelog.html
